package pt.unl.fct.di.adc.firstwebapp.resources;

import com.google.cloud.datastore.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import pt.unl.fct.di.adc.firstwebapp.util.ChangeUserRoleRequest;
import pt.unl.fct.di.adc.firstwebapp.util.ErrorResponse;
import pt.unl.fct.di.adc.firstwebapp.util.SuccessResponse;

import java.util.logging.Logger;

@Path("/changeuserrole")
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
public class ChangeUserRoleResource {

    private static final Logger LOG = Logger.getLogger(RegisterResource.class.getName());
    private static final Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
    private final Gson g = new GsonBuilder().setPrettyPrinting().create();
    private static final KeyFactory userKeyFactory = datastore.newKeyFactory().setKind("User");

    @POST
    @Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    public Response changeUserRole(ChangeUserRoleRequest request) {

        Key userKey = userKeyFactory.newKey(request.input.username);
        Entity user = datastore.get(userKey);

        if (user == null) {
            LOG.warning("User '" + request.input.username + "' does not exist.");

            // USER_NOT_FOUND
            ErrorResponse responseErr = new ErrorResponse("9902", "The username referred in the operation doesn’t exist in registered accounts");

            return Response.ok().entity(g.toJson(responseErr)).build();
        }

        // INVALID_TOKEN
        if (request.token == null || request.token.tokenId == null || request.token.tokenId.isBlank()) {
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        Key tokenKey = datastore.newKeyFactory().setKind("AuthToken").newKey(request.token.tokenId);
        Entity storedToken = datastore.get(tokenKey);

        if (storedToken == null) {
            // tokenId does not exist in datastore database, so the user is trying to autenticate with a token that was not generated by the server
            // also INVALID_TOKEN
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // TOKEN_EXPIRED
        if (System.currentTimeMillis() > request.token.expiresAt) {
            ErrorResponse errorResponse = new ErrorResponse("9904", "The operation is called with a token that is expired");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        String role = storedToken.getString("role");//get the token role from datastore
        if (role == null || !role.equals("ADMIN")) {
            // UNAUTHORIZED
            ErrorResponse errorResponse = new ErrorResponse("9905", "The operation is not allowed for the user role");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        if (!request.input.newRole.equals("ADMIN") && !request.input.newRole.equals("USER")
                && !request.input.newRole.equals("BOFFICER")) {
            // FORBIDDEN
            ErrorResponse errorResponse = new ErrorResponse("9907", "The operation generated a forbidden error by other reason");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // update the role that exists in the request
        Entity.Builder updatedUser = Entity.newBuilder(user);
        updatedUser.set("user_role", request.input.newRole);
        datastore.update(updatedUser.build());//save the updates to datastore

        // update the role on all active tokens of the user
        Query<Entity> tokenQuery = Query.newEntityQueryBuilder()
                .setKind("AuthToken")
                .setFilter(StructuredQuery.PropertyFilter.eq("username", request.input.username))
                .build();

        QueryResults<Entity> tokenResults = datastore.run(tokenQuery);

        while (tokenResults.hasNext()) {
            Entity currentToken = tokenResults.next();
            Entity updatedToken = Entity.newBuilder(currentToken)
                    .set("role", request.input.newRole)
                    .build();
            datastore.update(updatedToken);//save the updates to datastore
        }

        SuccessResponse response = new SuccessResponse("Role updated successfully");

        return Response.ok().entity(g.toJson(response)).build();
    }
}
