package pt.unl.fct.di.adc.firstwebapp.resources;


import com.google.cloud.datastore.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import org.apache.commons.codec.digest.DigestUtils;
import pt.unl.fct.di.adc.firstwebapp.util.*;

import java.util.logging.Logger;

@Path("/changeuserpwd")
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
public class ChangeUserPasswordResource {

    private static final Logger LOG = Logger.getLogger(RegisterResource.class.getName());
    private static final Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
    private final Gson g = new GsonBuilder().setPrettyPrinting().create();
    private static final KeyFactory userKeyFactory = datastore.newKeyFactory().setKind("User");

    @POST
    @Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    public Response changeUserRole(ChangeUserPasswordRequest request) {
        Key userKey = userKeyFactory.newKey(request.input.username);
        Entity user = datastore.get(userKey);

        if(user != null) {
            String hashedPWD = user.getString("user_pwd");
            if(hashedPWD.equals(DigestUtils.sha512Hex(request.input.oldPassword))) {
                LOG.info("User '" + request.input.username + "' logged in successfully.");

                // INVALID_TOKEN
                if (request.token == null || request.token.tokenId == null || request.token.tokenId.isBlank()) {
                    ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
                    return Response.ok().entity(g.toJson(errorResponse)).build();
                }

                Key tokenKey = datastore.newKeyFactory().setKind("AuthToken").newKey(request.token.tokenId);
                Entity storedToken = datastore.get(tokenKey);

                if (storedToken == null) {
                    // tokenId does not exist in datastore database, so the user is trying to autenticate with a token that was not generated by the server
                    // also INVALID_TOKEN
                    ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
                    return Response.ok().entity(g.toJson(errorResponse)).build();
                }

                // TOKEN_EXPIRED
                if (System.currentTimeMillis() > request.token.expiresAt) {
                    ErrorResponse errorResponse = new ErrorResponse("9904", "The operation is called with a token that is expired");
                    return Response.ok().entity(g.toJson(errorResponse)).build();
                }

                if (!request.token.username.equals(request.input.username)) {
                    // independentemente da role, cada conta só pode mudar a sua própria password
                    // UNAUTHORIZED
                    ErrorResponse errorResponse = new ErrorResponse("9905", "The operation is not allowed for the user role");
                    return Response.ok().entity(g.toJson(errorResponse)).build();
                }

                SuccessResponse response = new SuccessResponse("Password changed successfully");

                return Response.ok().entity(g.toJson(response)).build();
            }
            else {
                LOG.warning("User '" + request.input.username + "' provided wrong password.");

                // INVALID_CREDENTIALS
                ErrorResponse responseErr = new ErrorResponse("9900", "The username-password pair is not valid");

                return Response.ok().entity(g.toJson(responseErr)).build();
            }
        }
        else {
            LOG.warning("User '" + request.input.username + "' does not exist.");

            // FORBIDDEN e não USER_NOT_FOUND por causa da especificação do enunciado para esta operação

            ErrorResponse errorResponse = new ErrorResponse("9907", "The operation generated a forbidden error by other reason");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }
    }

}
