package pt.unl.fct.di.adc.firstwebapp.resources;

import com.google.cloud.datastore.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import pt.unl.fct.di.adc.firstwebapp.util.AccountRequest;
import pt.unl.fct.di.adc.firstwebapp.util.ErrorResponse;
import pt.unl.fct.di.adc.firstwebapp.util.SuccessResponse;

import java.util.logging.Logger;

@Path("/logout")
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
public class LogoutResource {

    private static final Logger LOG = Logger.getLogger(RegisterResource.class.getName());
    private static final Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
    private final Gson g = new GsonBuilder().setPrettyPrinting().create();
    private static final KeyFactory userKeyFactory = datastore.newKeyFactory().setKind("User");

    @POST
    @Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    public Response showUserRole(AccountRequest request) {

        // INVALID_TOKEN
        if (request.token == null || request.token.tokenId == null || request.token.tokenId.isBlank()) {
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        Key tokenKey = datastore.newKeyFactory().setKind("AuthToken").newKey(request.token.tokenId);
        Entity storedToken = datastore.get(tokenKey);

        if (storedToken == null) {
            // tokenId does not exist in datastore database, so the user is trying to autenticate with a token that was not generated by the server
            // also INVALID_TOKEN
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // TOKEN_EXPIRED
        if (System.currentTimeMillis() > request.token.expiresAt) {
            ErrorResponse errorResponse = new ErrorResponse("9904", "The operation is called with a token that is expired");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        String role = request.token.role;

        if (!role.equals("ADMIN") && !request.token.username.equals(request.input.username)) {
            // UNAUTHORIZED
            ErrorResponse errorResponse = new ErrorResponse("9905", "The operation is not allowed for the user role");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        //delete every token associated with this user
        Query<Entity> tokenQuery = Query.newEntityQueryBuilder().setKind("AuthToken")
                .setFilter(StructuredQuery.PropertyFilter.eq("username", request.input.username))
                .build();

        QueryResults<Entity> results = datastore.run(tokenQuery);
        while (results.hasNext()) {
            Entity token = results.next();
            datastore.delete(token.getKey());
        }

        SuccessResponse response = new SuccessResponse("Logout successful");

        return Response.ok().entity(g.toJson(response)).build();
    }
}
