package pt.unl.fct.di.adc.firstwebapp.resources;

import com.google.cloud.datastore.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import pt.unl.fct.di.adc.firstwebapp.util.ErrorResponse;
import pt.unl.fct.di.adc.firstwebapp.util.ModifyAccountAttributesRequest;
import pt.unl.fct.di.adc.firstwebapp.util.SuccessResponse;

import java.util.logging.Logger;

@Path("/modaccount")
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
public class ModifyAccountAttributesResource {// changes only phone and address fields

    private static final Logger LOG = Logger.getLogger(RegisterResource.class.getName());
    private static final Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
    private final Gson g = new GsonBuilder().setPrettyPrinting().create();
    private static final KeyFactory userKeyFactory = datastore.newKeyFactory().setKind("User");

    @POST
    @Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    public Response modifyAccountAttributes(ModifyAccountAttributesRequest request) {
        Key userKey = userKeyFactory.newKey(request.input.username);
        Entity user = datastore.get(userKey);

        if (user == null) {
            LOG.warning("User '" + request.input.username + "' does not exist.");

            // USER_NOT_FOUND
            ErrorResponse responseErr = new ErrorResponse("9902", "The username referred in the operation doesn’t exist in registered accounts");

            return Response.ok().entity(g.toJson(responseErr)).build();
        }

        // INVALID_TOKEN
        if (request.token == null || request.token.tokenId == null || request.token.tokenId.isBlank()) {
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        Key tokenKey = datastore.newKeyFactory().setKind("AuthToken").newKey(request.token.tokenId);
        Entity storedToken = datastore.get(tokenKey);

        if (storedToken == null) {
            // tokenId does not exist in datastore database, so the user is trying to autenticate with a token that was not generated by the server
            // also INVALID_TOKEN
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // TOKEN_EXPIRED
        if (System.currentTimeMillis() > request.token.expiresAt) {
            ErrorResponse errorResponse = new ErrorResponse("9904", "The operation is called with a token that is expired");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        String calerRole = storedToken.getString("role");//get the token role from datastore
        String targetRole = user.getString("user_role");

        if ((calerRole == null || (!calerRole.equals("ADMIN") && !calerRole.equals("BOFFICER") && !calerRole.equals("USER")))
        || (calerRole.equals("USER") && !request.token.username.equals(request.input.username))
        || (calerRole.equals("BOFFICER") && !request.token.username.equals(request.input.username) && !targetRole.equals("USER"))) {
            // UNAUTHORIZED
            ErrorResponse errorResponse = new ErrorResponse("9905", "The operation is not allowed for the user role");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // INVALID_INPUT
        boolean existsPhone = request.input.attributes != null && request.input.attributes.phone != null
                && !request.input.attributes.phone.isBlank() && isInteger(request.input.attributes.phone);

        boolean existsAddress = request.input.attributes != null && request.input.attributes.address != null
        && !request.input.attributes.address.isBlank();

        if ((!existsPhone && !existsAddress) || !isInteger(request.input.attributes.phone)) {
            // INVALID_INPUT
            ErrorResponse responseErr = new ErrorResponse("9906", "The call is using input data not following the correct specification");

            return Response.ok().entity(g.toJson(responseErr)).build();
        }

        // update the fields that exist in the request
        Entity.Builder updatedUser = Entity.newBuilder(user);
        if (existsPhone) {
            updatedUser.set("user_phone", request.input.attributes.phone);
        }
        if (existsAddress) {
            updatedUser.set("user_address", request.input.attributes.address);
        }
        datastore.update(updatedUser.build());//save the updates to datastore

        SuccessResponse response = new SuccessResponse("Updated successfully");

        return Response.ok().entity(g.toJson(response)).build();
    }

    public static boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
}
