package pt.unl.fct.di.adc.firstwebapp.resources;

import com.google.cloud.datastore.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import pt.unl.fct.di.adc.firstwebapp.util.ErrorResponse;
import pt.unl.fct.di.adc.firstwebapp.util.ShowAuthenticatedSessionsResponse;
import pt.unl.fct.di.adc.firstwebapp.util.ShowRequest;

import java.util.ArrayList;
import java.util.List;

@Path("/showauthsessions")
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
public class ShowAuthenticatedSessionsResource {

    private static final Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
    private final Gson g = new GsonBuilder().setPrettyPrinting().create();

    @POST
    @Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    public Response showAuthenticatedSessions(ShowRequest request) {

        // INVALID_TOKEN
        if (request.token == null || request.token.tokenId == null || request.token.tokenId.isBlank()) {
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        Key tokenKey = datastore.newKeyFactory().setKind("AuthToken").newKey(request.token.tokenId);
        Entity storedToken = datastore.get(tokenKey);

        if (storedToken == null) {
            // tokenId does not exist in datastore database, so the user is trying to autenticate with a token that was not generated by the server
            // also INVALID_TOKEN
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // TOKEN_EXPIRED
        if (System.currentTimeMillis() > request.token.expiresAt) {
            ErrorResponse errorResponse = new ErrorResponse("9904", "The operation is called with a token that is expired");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        String calerRole = storedToken.getString("role");//get the token role from datastore
        if (!calerRole.equals("ADMIN")) {
            // UNAUTHORIZED
            ErrorResponse errorResponse = new ErrorResponse("9905", "The operation is not allowed for the user role");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        Query<Entity> query = Query.newEntityQueryBuilder().setKind("AuthToken").build();

        QueryResults<Entity> results = datastore.run(query);

        List<ShowAuthenticatedSessionsResponse.Session> sessions = new ArrayList<>();
        while (results.hasNext()) {
            Entity tokenEntity = results.next();
            String tokenId = tokenEntity.getKey().getName();
            String username = tokenEntity.getString("username");
            String role = tokenEntity.getString("role");
            long expiresAt = tokenEntity.getLong("expiresAt");
            sessions.add(new ShowAuthenticatedSessionsResponse.Session(tokenId, username, role, expiresAt));
        }

        ShowAuthenticatedSessionsResponse response = new ShowAuthenticatedSessionsResponse(sessions);

        return Response.ok().entity(g.toJson(response)).build();
    }
}
