package pt.unl.fct.di.adc.firstwebapp.resources;

import com.google.cloud.datastore.*;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import com.google.gson.GsonBuilder;
import jakarta.ws.rs.core.Response;
import org.apache.commons.codec.digest.DigestUtils;

import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response.Status;

import com.google.gson.Gson;
import com.google.cloud.Timestamp;

import pt.unl.fct.di.adc.firstwebapp.util.*;

@Path("/showusers")
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
public class ShowUsersResource {

    private static final Logger LOG = Logger.getLogger(RegisterResource.class.getName());
    private static final Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
    private final Gson g = new GsonBuilder().setPrettyPrinting().create();

    @POST
    @Path("/") // previously v3
    @Consumes(MediaType.APPLICATION_JSON)
    public Response showUsers(ShowUsersRequest request) {

        Key tokenKey = datastore.newKeyFactory().setKind("AuthToken").newKey(request.token.tokenId);
        Entity storedToken = datastore.get(tokenKey);

        if (storedToken == null) {
            // tokenId does not exist in datastore database, so the user is trying to autenticate with a token that was not generated by the server
            //INVALID_TOKEN
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // INVALID_TOKEN
        if (request.token == null || request.token.tokenId == null || request.token.tokenId.isBlank()) {
            ErrorResponse errorResponse = new ErrorResponse("9903", "The operation is called with an invalid token (wrong format for example)");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // TOKEN_EXPIRED
        if (System.currentTimeMillis() > request.token.expiresAt) {
            ErrorResponse errorResponse = new ErrorResponse("9904", "The operation is called with a token that is expired");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        String role = request.token.role;
        if (role == null || (!role.equals("ADMIN") && !role.equals("BOFFICER"))) {
            // UNAUTHORIZED
            ErrorResponse errorResponse = new ErrorResponse("9905", "The operation is not allowed for the user role");
            return Response.ok().entity(g.toJson(errorResponse)).build();
        }

        // asks for all users in datastore database
        Query<Entity> query = Query.newEntityQueryBuilder()
                .setKind("User").build();

        QueryResults<Entity> results = datastore.run(query);

        List<ShowUsersResponse.UserResponse> users = new ArrayList<>();
        while (results.hasNext()) {
            Entity user = results.next();
            String username = user.getKey().getName();
            String userRole = user.getString("user_role");
            users.add(new ShowUsersResponse.UserResponse(username, userRole));
        }

        ShowUsersResponse response = new ShowUsersResponse(users);

        return Response.ok().entity(g.toJson(response)).build();
    }
}
